server:
  port: 8180
spring:
  redis:
    host: 192.168.40.16 #redis地址
    port: 6379  #端口
    password:   #密码
    jedis:
      pool:
        max-active: 8 #连接池最大连接数
        max-wait: -1  #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8   #连接池最大空闲连接
        min-idle: 0   #连接池最小空闲连接
    timeout: 10000    #连接超时时间（毫秒）